### ISSUE TITLE
Add choices to generate MCE Cape code

### ISSUE THREAD

**Issue by Rddff123** [NotAGanesh/5x5-code-generator#1]
import random

def generate_code():
    allowed_chars = "2346789BCDFGHJKMNPQRTVWXYZ"
    codes = []

    while len(codes) < 25:  # Generate 25 codes
        code = "2" + "".join(random.choices(allowed_chars, k=4)) + "-" + \ #MC Experience code
               "-".join("".join(random.choices(allowed_chars, k=5)) for _ in range(3)) + "-" + \
               "".join(random.choices(allowed_chars, k=4)) + "Z"

        # Check for three consecutive repeated characters
        if all(code[i:i+3] != code[i+3:i+6] for i in range(len(code) - 6)):
            codes.append(code)

    return codes

# Generate and print 25 codes
for code in generate_code():
    print(code)    

Generating codes SPECIALIZED for MC experience cape code

**Comment by Rddff123** [comment]
SOrry if it sounds not polite

**Comment by NotAGanesh** [comment]
Code might be broken. but your idea is great

**Comment by NotAGanesh** [comment]
fixed version
```
import random

def generate_code(num_codes=25):
    """Generates a list of unique codes based on the specified format.

    Args:
        num_codes: The desired number of unique codes.

    Returns:
        A list of unique codes.
    """

    allowed_chars = "2346789BCDFGHJKMNPQRTVWXYZ"
    codes = []

    while len(codes) < num_codes:
        code = "2" + "".join(random.choices(allowed_chars, k=4)) + "-" + \
               "-".join("".join(random.choices(allowed_chars, k=5)) for _ in range(3)) + "-" + \
               "".join(random.choices(allowed_chars, k=4)) + "Z"

        if not any(code[i:i+3] == code[i+3:i+6] for i in range(len(code) - 6)):
            codes.append(code)

    return codes

# Generate and print 25 unique codes
for code in generate_code():
    print(code)
```

**Comment by NotAGanesh** [comment]
and i question what does mce means?

**Comment by NotAGanesh** [comment]
compressed version
```
F=range
import random as B
def A(num_codes=25):
	E='-';C='2346789BCDFGHJKMNPQRTVWXYZ';D=[]
	while len(D)<num_codes:
		A='2'+''.join(B.choices(C,k=4))+E+E.join(''.join(B.choices(C,k=5))for A in F(3))+E+''.join(B.choices(C,k=4))+'Z'
		if not any(A[B:B+3]==A[B+3:B+6]for B in F(len(A)-6)):D.append(A)
	return D
for C in A():print(C)
```

**Comment by NotAGanesh** [comment]
this idea will be add soon

**Comment by Rddff123** [comment]
Thanks! I don't know why when I added the code it broke...
MCE means the Minecraft Experience event (i don't know why, so many people seems to be crazy about it) and the code I provided is to generate the "cape code" of the events.
